import { Recipe } from "@/app/components/RecipeBook";

export const recipes: Recipe[] = [
  // CHINESE CUISINE
  {
    id: '6',
    name: 'Vegetable Fried Rice',
    category: 'Rice & Noodles',
    cuisine: 'Chinese',
    description: 'Quick and delicious Indo-Chinese style fried rice with colorful vegetables',
    prepTime: '15 mins',
    cookTime: '15 mins',
    ingredients: [
      { name: 'Cooked Rice (cold)', quantity: '200g' },
      { name: 'Carrots (diced)', quantity: '2 tbsp' },
      { name: 'Green Beans (chopped)', quantity: '2 tbsp' },
      { name: 'Green Peas', quantity: '2 tbsp' },
      { name: 'Bell Pepper (diced)', quantity: '2 tbsp' },
      { name: 'Spring Onions', quantity: '2 stalks' },
      { name: 'Garlic (minced)', quantity: '2 cloves' },
      { name: 'Ginger (minced)', quantity: '1/2 tsp' },
      { name: 'Soy Sauce', quantity: '1 tbsp' },
      { name: 'Green Chili (optional)', quantity: '1 small' },
      { name: 'Vegetable Oil', quantity: '2 tbsp' },
      { name: 'Salt', quantity: 'to taste' },
      { name: 'Black Pepper', quantity: '1/4 tsp' },
      { name: 'Vinegar', quantity: '1/2 tsp' },
    ],
    instructions: [
      'Ensure rice is cooked and completely cooled (preferably refrigerated overnight).',
      'Heat oil in a wok or large pan over high heat until smoking hot.',
      'Add minced garlic, ginger, and chopped green chili. Stir-fry for 30 seconds.',
      'Add all diced vegetables and stir-fry for 2-3 minutes until slightly tender.',
      'Add the white parts of spring onions and stir-fry for another minute.',
      'Push vegetables to the side and add cold rice to the center. Break up any clumps.',
      'Add soy sauce, salt, pepper, and vinegar. Toss vigorously for 3-4 minutes.',
      'Ensure rice is heated through and well-coated with sauces.',
      'Add green parts of spring onions and give a final toss.',
      'Serve immediately while hot.',
    ],
  },
  {
    id: '7',
    name: 'Hakka Noodles',
    category: 'Rice & Noodles',
    cuisine: 'Chinese',
    description: 'Stir-fried noodles with vegetables and Indo-Chinese seasonings',
    prepTime: '15 mins',
    cookTime: '12 mins',
    ingredients: [
      { name: 'Hakka Noodles', quantity: '150g' },
      { name: 'Cabbage (shredded)', quantity: '1/2 cup' },
      { name: 'Carrots (julienned)', quantity: '1/4 cup' },
      { name: 'Bell Peppers', quantity: '1/4 cup' },
      { name: 'Spring Onions', quantity: '2 stalks' },
      { name: 'Garlic (minced)', quantity: '3 cloves' },
      { name: 'Soy Sauce', quantity: '2 tbsp' },
      { name: 'Chili Sauce', quantity: '1 tbsp' },
      { name: 'Vinegar', quantity: '1 tsp' },
      { name: 'Vegetable Oil', quantity: '2 tbsp' },
      { name: 'Black Pepper', quantity: '1/2 tsp' },
      { name: 'Salt', quantity: 'to taste' },
    ],
    instructions: [
      'Boil noodles according to package instructions. Drain and toss with a little oil.',
      'Heat oil in a wok over high heat. Add minced garlic and stir-fry for 30 seconds.',
      'Add all vegetables and stir-fry for 2-3 minutes on high heat.',
      'Add soy sauce, chili sauce, vinegar, salt, and pepper. Mix well.',
      'Add boiled noodles and toss everything together for 2-3 minutes.',
      'Add spring onions and give a final toss.',
      'Serve hot with additional chili sauce if desired.',
    ],
  },
  {
    id: '8',
    name: 'Manchurian',
    category: 'Appetizer',
    cuisine: 'Chinese',
    description: 'Crispy vegetable balls in a tangy Indo-Chinese sauce',
    prepTime: '25 mins',
    cookTime: '20 mins',
    ingredients: [
      { name: 'Cabbage (grated)', quantity: '1 cup' },
      { name: 'Carrots (grated)', quantity: '1/4 cup' },
      { name: 'Cornflour', quantity: '4 tbsp' },
      { name: 'All-Purpose Flour', quantity: '2 tbsp' },
      { name: 'Ginger-Garlic Paste', quantity: '1 tsp' },
      { name: 'Soy Sauce', quantity: '2 tbsp' },
      { name: 'Tomato Ketchup', quantity: '2 tbsp' },
      { name: 'Chili Sauce', quantity: '1 tbsp' },
      { name: 'Spring Onions', quantity: '2 stalks' },
      { name: 'Vegetable Oil', quantity: 'for frying' },
      { name: 'Salt', quantity: 'to taste' },
      { name: 'Black Pepper', quantity: '1/2 tsp' },
    ],
    instructions: [
      'Mix grated cabbage, carrots, cornflour, flour, salt, and pepper. Form small balls.',
      'Deep fry the balls until golden and crispy. Drain on paper towels.',
      'Heat 1 tbsp oil in a pan, add ginger-garlic paste and sauté.',
      'Add soy sauce, ketchup, chili sauce, and 1/2 cup water. Bring to boil.',
      'Mix 1 tbsp cornflour with water and add to thicken the sauce.',
      'Add fried balls to the sauce and toss to coat.',
      'Garnish with spring onions and serve hot.',
    ],
  },
  {
    id: '9',
    name: 'Sweet and Sour Chicken',
    category: 'Main Course',
    cuisine: 'Chinese',
    description: 'Crispy chicken in a tangy sweet and sour sauce with vegetables',
    prepTime: '20 mins',
    cookTime: '20 mins',
    ingredients: [
      { name: 'Chicken (boneless)', quantity: '200g' },
      { name: 'Bell Peppers (cubed)', quantity: '1/2 cup' },
      { name: 'Pineapple (cubed)', quantity: '1/4 cup' },
      { name: 'Onions (cubed)', quantity: '1/2 medium' },
      { name: 'Cornflour', quantity: '3 tbsp' },
      { name: 'Tomato Ketchup', quantity: '3 tbsp' },
      { name: 'Soy Sauce', quantity: '1 tbsp' },
      { name: 'Vinegar', quantity: '2 tbsp' },
      { name: 'Sugar', quantity: '2 tbsp' },
      { name: 'Garlic (minced)', quantity: '2 cloves' },
      { name: 'Vegetable Oil', quantity: 'for frying' },
      { name: 'Salt', quantity: 'to taste' },
    ],
    instructions: [
      'Cut chicken into bite-sized pieces. Coat with cornflour, salt, and pepper.',
      'Deep fry chicken until golden and crispy. Set aside.',
      'Heat 1 tbsp oil in a wok, add garlic and sauté for 30 seconds.',
      'Add bell peppers and onions, stir-fry for 2 minutes.',
      'Mix ketchup, soy sauce, vinegar, sugar, and 1/2 cup water. Add to wok.',
      'Bring to boil and add cornflour slurry to thicken.',
      'Add fried chicken and pineapple pieces. Toss to coat.',
      'Serve hot with fried rice or noodles.',
    ],
  },
  {
    id: '10',
    name: 'Chili Garlic Fried Rice',
    category: 'Rice & Noodles',
    cuisine: 'Chinese',
    description: 'Spicy garlic-infused fried rice with a fiery kick',
    prepTime: '10 mins',
    cookTime: '12 mins',
    ingredients: [
      { name: 'Cooked Rice (cold)', quantity: '200g' },
      { name: 'Garlic (minced)', quantity: '6 cloves' },
      { name: 'Green Chilies (chopped)', quantity: '3' },
      { name: 'Spring Onions', quantity: '2 stalks' },
      { name: 'Soy Sauce', quantity: '2 tbsp' },
      { name: 'Chili Sauce', quantity: '2 tbsp' },
      { name: 'Vinegar', quantity: '1 tsp' },
      { name: 'Vegetable Oil', quantity: '2 tbsp' },
      { name: 'Salt', quantity: 'to taste' },
      { name: 'Black Pepper', quantity: '1/2 tsp' },
    ],
    instructions: [
      'Heat oil in a wok until smoking hot.',
      'Add minced garlic and green chilies, stir-fry for 30 seconds.',
      'Add white parts of spring onions and sauté for 1 minute.',
      'Add cold rice and break up any clumps.',
      'Add soy sauce, chili sauce, vinegar, salt, and pepper.',
      'Toss vigorously for 3-4 minutes on high heat.',
      'Add green parts of spring onions and mix.',
      'Serve hot as is or with a side of Manchurian.',
    ],
  },

  // ITALIAN CUISINE
  {
    id: '6',
    name: 'Vegetable Fried Rice',
    category: 'Rice & Noodles',
    cuisine: 'Chinese',
    description: 'Quick and delicious Indo-Chinese style fried rice with colorful vegetables',
    prepTime: '15 mins',
    cookTime: '15 mins',
    ingredients: [
      { name: 'Cooked Rice (cold)', quantity: '200g' },
      { name: 'Carrots (diced)', quantity: '2 tbsp' },
      { name: 'Green Beans (chopped)', quantity: '2 tbsp' },
      { name: 'Green Peas', quantity: '2 tbsp' },
      { name: 'Bell Pepper (diced)', quantity: '2 tbsp' },
      { name: 'Spring Onions', quantity: '2 stalks' },
      { name: 'Garlic (minced)', quantity: '2 cloves' },
      { name: 'Ginger (minced)', quantity: '1/2 tsp' },
      { name: 'Soy Sauce', quantity: '1 tbsp' },
      { name: 'Green Chili (optional)', quantity: '1 small' },
      { name: 'Vegetable Oil', quantity: '2 tbsp' },
      { name: 'Salt', quantity: 'to taste' },
      { name: 'Black Pepper', quantity: '1/4 tsp' },
      { name: 'Vinegar', quantity: '1/2 tsp' },
    ],
    instructions: [
      'Ensure rice is cooked and completely cooled (preferably refrigerated overnight).',
      'Heat oil in a wok or large pan over high heat until smoking hot.',
      'Add minced garlic, ginger, and chopped green chili. Stir-fry for 30 seconds.',
      'Add all diced vegetables and stir-fry for 2-3 minutes until slightly tender.',
      'Add the white parts of spring onions and stir-fry for another minute.',
      'Push vegetables to the side and add cold rice to the center. Break up any clumps.',
      'Add soy sauce, salt, pepper, and vinegar. Toss vigorously for 3-4 minutes.',
      'Ensure rice is heated through and well-coated with sauces.',
      'Add green parts of spring onions and give a final toss.',
      'Serve immediately while hot.',
    ],
  },
  {
    id: '7',
    name: 'Hakka Noodles',
    category: 'Rice & Noodles',
    cuisine: 'Chinese',
    description: 'Stir-fried noodles with vegetables and Indo-Chinese seasonings',
    prepTime: '15 mins',
    cookTime: '12 mins',
    ingredients: [
      { name: 'Hakka Noodles', quantity: '150g' },
      { name: 'Cabbage (shredded)', quantity: '1/2 cup' },
      { name: 'Carrots (julienned)', quantity: '1/4 cup' },
      { name: 'Bell Peppers', quantity: '1/4 cup' },
      { name: 'Spring Onions', quantity: '2 stalks' },
      { name: 'Garlic (minced)', quantity: '3 cloves' },
      { name: 'Soy Sauce', quantity: '2 tbsp' },
      { name: 'Chili Sauce', quantity: '1 tbsp' },
      { name: 'Vinegar', quantity: '1 tsp' },
      { name: 'Vegetable Oil', quantity: '2 tbsp' },
      { name: 'Black Pepper', quantity: '1/2 tsp' },
      { name: 'Salt', quantity: 'to taste' },
    ],
    instructions: [
      'Boil noodles according to package instructions. Drain and toss with a little oil.',
      'Heat oil in a wok over high heat. Add minced garlic and stir-fry for 30 seconds.',
      'Add all vegetables and stir-fry for 2-3 minutes on high heat.',
      'Add soy sauce, chili sauce, vinegar, salt, and pepper. Mix well.',
      'Add boiled noodles and toss everything together for 2-3 minutes.',
      'Add spring onions and give a final toss.',
      'Serve hot with additional chili sauce if desired.',
    ],
  },
  {
    id: '8',
    name: 'Manchurian',
    category: 'Appetizer',
    cuisine: 'Chinese',
    description: 'Crispy vegetable balls in a tangy Indo-Chinese sauce',
    prepTime: '25 mins',
    cookTime: '20 mins',
    ingredients: [
      { name: 'Cabbage (grated)', quantity: '1 cup' },
      { name: 'Carrots (grated)', quantity: '1/4 cup' },
      { name: 'Cornflour', quantity: '4 tbsp' },
      { name: 'All-Purpose Flour', quantity: '2 tbsp' },
      { name: 'Ginger-Garlic Paste', quantity: '1 tsp' },
      { name: 'Soy Sauce', quantity: '2 tbsp' },
      { name: 'Tomato Ketchup', quantity: '2 tbsp' },
      { name: 'Chili Sauce', quantity: '1 tbsp' },
      { name: 'Spring Onions', quantity: '2 stalks' },
      { name: 'Vegetable Oil', quantity: 'for frying' },
      { name: 'Salt', quantity: 'to taste' },
      { name: 'Black Pepper', quantity: '1/2 tsp' },
    ],
    instructions: [
      'Mix grated cabbage, carrots, cornflour, flour, salt, and pepper. Form small balls.',
      'Deep fry the balls until golden and crispy. Drain on paper towels.',
      'Heat 1 tbsp oil in a pan, add ginger-garlic paste and sauté.',
      'Add soy sauce, ketchup, chili sauce, and 1/2 cup water. Bring to boil.',
      'Mix 1 tbsp cornflour with water and add to thicken the sauce.',
      'Add fried balls to the sauce and toss to coat.',
      'Garnish with spring onions and serve hot.',
    ],
  },
  {
    id: '9',
    name: 'Sweet and Sour Chicken',
    category: 'Main Course',
    cuisine: 'Chinese',
    description: 'Crispy chicken in a tangy sweet and sour sauce with vegetables',
    prepTime: '20 mins',
    cookTime: '20 mins',
    ingredients: [
      { name: 'Chicken (boneless)', quantity: '200g' },
      { name: 'Bell Peppers (cubed)', quantity: '1/2 cup' },
      { name: 'Pineapple (cubed)', quantity: '1/4 cup' },
      { name: 'Onions (cubed)', quantity: '1/2 medium' },
      { name: 'Cornflour', quantity: '3 tbsp' },
      { name: 'Tomato Ketchup', quantity: '3 tbsp' },
      { name: 'Soy Sauce', quantity: '1 tbsp' },
      { name: 'Vinegar', quantity: '2 tbsp' },
      { name: 'Sugar', quantity: '2 tbsp' },
      { name: 'Garlic (minced)', quantity: '2 cloves' },
      { name: 'Vegetable Oil', quantity: 'for frying' },
      { name: 'Salt', quantity: 'to taste' },
    ],
    instructions: [
      'Cut chicken into bite-sized pieces. Coat with cornflour, salt, and pepper.',
      'Deep fry chicken until golden and crispy. Set aside.',
      'Heat 1 tbsp oil in a wok, add garlic and sauté for 30 seconds.',
      'Add bell peppers and onions, stir-fry for 2 minutes.',
      'Mix ketchup, soy sauce, vinegar, sugar, and 1/2 cup water. Add to wok.',
      'Bring to boil and add cornflour slurry to thicken.',
      'Add fried chicken and pineapple pieces. Toss to coat.',
      'Serve hot with fried rice or noodles.',
    ],
  },
  {
    id: '10',
    name: 'Chili Garlic Fried Rice',
    category: 'Rice & Noodles',
    cuisine: 'Chinese',
    description: 'Spicy garlic-infused fried rice with a fiery kick',
    prepTime: '10 mins',
    cookTime: '12 mins',
    ingredients: [
      { name: 'Cooked Rice (cold)', quantity: '200g' },
      { name: 'Garlic (minced)', quantity: '6 cloves' },
      { name: 'Green Chilies (chopped)', quantity: '3' },
      { name: 'Spring Onions', quantity: '2 stalks' },
      { name: 'Soy Sauce', quantity: '2 tbsp' },
      { name: 'Chili Sauce', quantity: '2 tbsp' },
      { name: 'Vinegar', quantity: '1 tsp' },
      { name: 'Vegetable Oil', quantity: '2 tbsp' },
      { name: 'Salt', quantity: 'to taste' },
      { name: 'Black Pepper', quantity: '1/2 tsp' },
    ],
    instructions: [
      'Heat oil in a wok until smoking hot.',
      'Add minced garlic and green chilies, stir-fry for 30 seconds.',
      'Add white parts of spring onions and sauté for 1 minute.',
      'Add cold rice and break up any clumps.',
      'Add soy sauce, chili sauce, vinegar, salt, and pepper.',
      'Toss vigorously for 3-4 minutes on high heat.',
      'Add green parts of spring onions and mix.',
      'Serve hot as is or with a side of Manchurian.',
    ],
  },

  // ITALIAN CUISINE
  {
    id: '11',
    name: 'Spaghetti Carbonara',
    category: 'Pasta',
    cuisine: 'Italian',
    description: 'Classic Roman pasta with eggs, cheese, and crispy bacon',
    prepTime: '10 mins',
    cookTime: '15 mins',
    ingredients: [
      { name: 'Spaghetti', quantity: '150g' },
      { name: 'Bacon/Pancetta', quantity: '80g' },
      { name: 'Eggs', quantity: '2 large' },
      { name: 'Parmesan Cheese', quantity: '40g' },
      { name: 'Black Pepper', quantity: '1 tsp' },
      { name: 'Garlic (optional)', quantity: '1 clove' },
      { name: 'Salt', quantity: 'to taste' },
      { name: 'Olive Oil', quantity: '1 tbsp' },
    ],
    instructions: [
      'Boil spaghetti in salted water according to package instructions. Reserve 1 cup pasta water.',
      'Cut bacon into small pieces and fry until crispy.',
      'Beat eggs with grated parmesan cheese and black pepper.',
      'Drain pasta and add to the bacon pan (off heat).',
      'Quickly add egg mixture and toss vigorously. The heat will cook the eggs.',
      'Add pasta water gradually to create a creamy sauce.',
      'Season with more black pepper and parmesan.',
      'Serve immediately while hot.',
    ],
  },
  {
    id: '12',
    name: 'Margherita Pizza',
    category: 'Pizza',
    cuisine: 'Italian',
    description: 'Classic pizza with tomato sauce, mozzarella, and fresh basil',
    prepTime: '90 mins',
    cookTime: '12 mins',
    ingredients: [
      { name: 'Pizza Dough', quantity: '1 ball' },
      { name: 'Tomato Sauce', quantity: '1/2 cup' },
      { name: 'Mozzarella Cheese', quantity: '150g' },
      { name: 'Fresh Basil', quantity: '8-10 leaves' },
      { name: 'Olive Oil', quantity: '2 tbsp' },
      { name: 'Garlic (minced)', quantity: '2 cloves' },
      { name: 'Salt', quantity: 'to taste' },
      { name: 'Oregano', quantity: '1 tsp' },
    ],
    instructions: [
      'Preheat oven to 250°C (480°F).',
      'Roll out pizza dough to desired thickness on a floured surface.',
      'Spread tomato sauce evenly, leaving a border for the crust.',
      'Tear mozzarella and distribute evenly over sauce.',
      'Drizzle with olive oil and sprinkle oregano.',
      'Bake for 10-12 minutes until crust is golden and cheese is bubbly.',
      'Remove from oven and top with fresh basil leaves.',
      'Drizzle more olive oil and serve hot.',
    ],
  },
  {
    id: '13',
    name: 'Fettuccine Alfredo',
    category: 'Pasta',
    cuisine: 'Italian',
    description: 'Creamy pasta with butter, cream, and parmesan cheese',
    prepTime: '10 mins',
    cookTime: '15 mins',
    ingredients: [
      { name: 'Fettuccine', quantity: '150g' },
      { name: 'Heavy Cream', quantity: '1 cup' },
      { name: 'Butter', quantity: '3 tbsp' },
      { name: 'Parmesan Cheese', quantity: '60g' },
      { name: 'Garlic (minced)', quantity: '2 cloves' },
      { name: 'Black Pepper', quantity: '1/2 tsp' },
      { name: 'Nutmeg', quantity: 'pinch' },
      { name: 'Salt', quantity: 'to taste' },
      { name: 'Parsley', quantity: 'for garnish' },
    ],
    instructions: [
      'Cook fettuccine in salted boiling water until al dente. Reserve 1 cup pasta water.',
      'Melt butter in a large pan over medium heat. Add minced garlic and sauté.',
      'Add heavy cream and bring to a gentle simmer.',
      'Add grated parmesan cheese and stir until melted.',
      'Add cooked pasta to the sauce and toss to coat.',
      'Add pasta water if needed to adjust consistency.',
      'Season with black pepper, nutmeg, and salt.',
      'Garnish with parsley and extra parmesan. Serve immediately.',
    ],
  },
  {
    id: '14',
    name: 'Lasagna',
    category: 'Pasta',
    cuisine: 'Italian',
    description: 'Layered pasta with meat sauce, béchamel, and cheese',
    prepTime: '30 mins',
    cookTime: '45 mins',
    ingredients: [
      { name: 'Lasagna Sheets', quantity: '8 sheets' },
      { name: 'Ground Beef', quantity: '200g' },
      { name: 'Tomato Sauce', quantity: '2 cups' },
      { name: 'Mozzarella Cheese', quantity: '200g' },
      { name: 'Parmesan Cheese', quantity: '50g' },
      { name: 'Onions (chopped)', quantity: '1 medium' },
      { name: 'Garlic (minced)', quantity: '3 cloves' },
      { name: 'Béchamel Sauce', quantity: '2 cups' },
      { name: 'Olive Oil', quantity: '2 tbsp' },
      { name: 'Italian Herbs', quantity: '1 tsp' },
      { name: 'Salt', quantity: 'to taste' },
      { name: 'Black Pepper', quantity: '1/2 tsp' },
    ],
    instructions: [
      'Cook ground beef with onions and garlic until browned.',
      'Add tomato sauce, Italian herbs, salt, and pepper. Simmer for 15 minutes.',
      'Boil lasagna sheets if required (check package instructions).',
      'In a baking dish, spread a thin layer of meat sauce.',
      'Layer lasagna sheets, meat sauce, béchamel, and cheeses.',
      'Repeat layers 2-3 times, ending with béchamel and cheese on top.',
      'Cover with foil and bake at 180°C for 30 minutes.',
      'Remove foil and bake for 15 more minutes until golden.',
      'Let rest for 10 minutes before slicing and serving.',
    ],
  },
  {
    id: '15',
    name: 'Penne Arrabbiata',
    category: 'Pasta',
    cuisine: 'Italian',
    description: 'Spicy tomato-based pasta with garlic and red chili',
    prepTime: '10 mins',
    cookTime: '20 mins',
    ingredients: [
      { name: 'Penne Pasta', quantity: '150g' },
      { name: 'Tomatoes (crushed)', quantity: '2 cups' },
      { name: 'Garlic (minced)', quantity: '4 cloves' },
      { name: 'Red Chili Flakes', quantity: '1 tsp' },
      { name: 'Olive Oil', quantity: '3 tbsp' },
      { name: 'Fresh Basil', quantity: '6-8 leaves' },
      { name: 'Parmesan Cheese', quantity: '2 tbsp' },
      { name: 'Salt', quantity: 'to taste' },
      { name: 'Black Pepper', quantity: '1/2 tsp' },
    ],
    instructions: [
      'Cook penne in salted boiling water until al dente. Reserve pasta water.',
      'Heat olive oil in a pan, add minced garlic and red chili flakes.',
      'Sauté for 1 minute until fragrant (don\'t burn garlic).',
      'Add crushed tomatoes, salt, and pepper. Simmer for 12-15 minutes.',
      'Add cooked pasta to the sauce and toss well.',
      'Add pasta water if needed to adjust consistency.',
      'Tear fresh basil and add to the pasta.',
      'Serve hot with grated parmesan on top.',
    ],
  },
  {
    id: '15a',
    name: 'Risotto Milanese',
    category: 'Main Course',
    cuisine: 'Italian',
    description: 'Creamy saffron-infused rice dish from Milan',
    prepTime: '10 mins',
    cookTime: '25 mins',
    ingredients: [
      { name: 'Arborio Rice', quantity: '200g' },
      { name: 'Chicken Stock', quantity: '4 cups' },
      { name: 'White Wine', quantity: '1/2 cup' },
      { name: 'Onion (finely chopped)', quantity: '1 small' },
      { name: 'Saffron Threads', quantity: '1/4 tsp' },
      { name: 'Parmesan Cheese', quantity: '1/2 cup' },
      { name: 'Butter', quantity: '3 tbsp' },
      { name: 'Olive Oil', quantity: '2 tbsp' },
      { name: 'Salt', quantity: 'to taste' },
      { name: 'Black Pepper', quantity: '1/4 tsp' },
    ],
    instructions: [
      'Heat chicken stock in a pot and keep warm. Soak saffron in 2 tbsp warm stock.',
      'In a large pan, heat olive oil and 1 tbsp butter. Sauté onion until translucent.',
      'Add arborio rice and toast for 2 minutes, stirring constantly.',
      'Pour in white wine and stir until absorbed.',
      'Add warm stock one ladle at a time, stirring frequently.',
      'Continue adding stock and stirring until rice is creamy and al dente (about 18-20 minutes).',
      'Add saffron with its soaking liquid 5 minutes before rice is done.',
      'Remove from heat, stir in remaining butter and parmesan cheese.',
      'Season with salt and pepper. Let rest for 2 minutes before serving.',
    ],
  },
  {
    id: '15b',
    name: 'Tiramisu',
    category: 'Dessert',
    cuisine: 'Italian',
    description: 'Classic Italian coffee-flavored dessert with mascarpone',
    prepTime: '30 mins',
    cookTime: '0 mins',
    ingredients: [
      { name: 'Mascarpone Cheese', quantity: '250g' },
      { name: 'Eggs', quantity: '3 large' },
      { name: 'Sugar', quantity: '3 tbsp' },
      { name: 'Ladyfinger Biscuits', quantity: '200g' },
      { name: 'Strong Espresso (cooled)', quantity: '1 cup' },
      { name: 'Cocoa Powder', quantity: '2 tbsp' },
      { name: 'Coffee Liqueur (optional)', quantity: '2 tbsp' },
      { name: 'Vanilla Extract', quantity: '1 tsp' },
    ],
    instructions: [
      'Separate egg yolks from whites. Beat yolks with sugar until pale and creamy.',
      'Add mascarpone cheese to yolk mixture and beat until smooth.',
      'In a separate bowl, whip egg whites until stiff peaks form.',
      'Gently fold whipped egg whites into mascarpone mixture.',
      'Mix espresso with coffee liqueur (if using) in a shallow dish.',
      'Quickly dip ladyfingers in coffee mixture and arrange in a single layer in dish.',
      'Spread half of mascarpone mixture over ladyfingers.',
      'Add another layer of dipped ladyfingers and top with remaining mascarpone.',
      'Refrigerate for at least 4 hours. Dust with cocoa powder before serving.',
    ],
  },
  {
    id: '15c',
    name: 'Osso Buco',
    category: 'Main Course',
    cuisine: 'Italian',
    description: 'Milanese braised veal shanks in a rich vegetable and wine sauce',
    prepTime: '20 mins',
    cookTime: '2 hours',
    ingredients: [
      { name: 'Veal Shanks', quantity: '4 pieces' },
      { name: 'All-Purpose Flour', quantity: '½ cup' },
      { name: 'Olive Oil', quantity: '3 tbsp' },
      { name: 'Butter', quantity: '2 tbsp' },
      { name: 'Onion (diced)', quantity: '1 large' },
      { name: 'Carrots (diced)', quantity: '2 medium' },
      { name: 'Celery (diced)', quantity: '2 stalks' },
      { name: 'Garlic', quantity: '4 cloves' },
      { name: 'White Wine', quantity: '1 cup' },
      { name: 'Beef Stock', quantity: '2 cups' },
      { name: 'Canned Tomatoes', quantity: '400g' },
      { name: 'Fresh Thyme', quantity: '3 sprigs' },
      { name: 'Bay Leaves', quantity: '2 leaves' },
      { name: 'Lemon Zest', quantity: '1 lemon' },
      { name: 'Fresh Parsley (chopped)', quantity: '¼ cup' },
      { name: 'Salt', quantity: 'to taste' },
      { name: 'Black Pepper', quantity: 'to taste' },
    ],
    instructions: [
      'Season veal shanks with salt and pepper, then dredge in flour.',
      'Heat olive oil and butter in a heavy pot. Brown veal shanks on all sides, then set aside.',
      'In the same pot, add onions, carrots, and celery. Sauté until softened.',
      'Add garlic and cook for 1 minute until fragrant.',
      'Pour in white wine and deglaze the pot, scraping up browned bits.',
      'Add tomatoes, beef stock, thyme, and bay leaves. Bring to a simmer.',
      'Return veal shanks to the pot. Cover and braise in a 325°F oven for 2 hours.',
      'Check occasionally and turn shanks halfway through cooking.',
      'Make gremolata: Mix lemon zest, parsley, and a minced garlic clove.',
      'Remove shanks carefully (meat should be falling off bone). Reduce sauce if needed.',
      'Serve osso buco topped with gremolata, traditionally with risotto Milanese.',
    ],
  },
  {
    id: '15d',
    name: 'Panna Cotta',
    category: 'Dessert',
    cuisine: 'Italian',
    description: 'Silky smooth Italian cream dessert with berry compote',
    prepTime: '15 mins',
    cookTime: '5 mins',
    ingredients: [
      { name: 'Heavy Cream', quantity: '2 cups' },
      { name: 'Whole Milk', quantity: '1 cup' },
      { name: 'Sugar', quantity: '½ cup' },
      { name: 'Vanilla Bean (or extract)', quantity: '1 pod' },
      { name: 'Gelatin Powder', quantity: '2½ tsp' },
      { name: 'Cold Water', quantity: '3 tbsp' },
      { name: 'Fresh Berries (for topping)', quantity: '1 cup' },
      { name: 'Mint Leaves (for garnish)', quantity: 'a few' },
    ],
    instructions: [
      'Sprinkle gelatin over cold water in a small bowl and let bloom for 5 minutes.',
      'In a saucepan, combine cream, milk, and sugar. Split vanilla bean and scrape seeds into mixture.',
      'Heat cream mixture over medium heat until it just begins to simmer (do not boil).',
      'Remove from heat and add bloomed gelatin. Stir until completely dissolved.',
      'Strain mixture through a fine-mesh sieve to remove vanilla pod and any lumps.',
      'Pour mixture into ramekins or molds. Let cool to room temperature.',
      'Cover with plastic wrap and refrigerate for at least 4 hours or overnight until set.',
      'To serve, run a knife around edge and invert onto plates, or serve in ramekins.',
      'Top with fresh berries and garnish with mint leaves.',
    ],
  },
];